test_avg (__main__.TestArryCalc) ... FAIL
test_first (__main__.TestArryCalc) ... ok
test_getter (__main__.TestArryCalc) ... FAIL
test_last (__main__.TestArryCalc) ... FAIL

======================================================================
FAIL: test_avg (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_F1.py", line 86, in test_avg
    self.assertEqual(2, test_avg_b.avg())
AssertionError: 2 != 1.0

======================================================================
FAIL: test_getter (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_F1.py", line 47, in test_getter
    self.assertEqual([1,2,3], test_getter_b.getter())
AssertionError: Lists differ: [1, 2, 3] != [1, 2, 0]

First differing element 2:
3
0

- [1, 2, 3]
?        ^

+ [1, 2, 0]
?        ^


======================================================================
FAIL: test_last (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_F1.py", line 73, in test_last
    self.assertEqual(3, test_last_b.last())
AssertionError: 3 != 0

----------------------------------------------------------------------
Ran 4 tests in 0.065s

FAILED (failures=3)
