test_avg (__main__.TestArryCalc) ... ok
test_first (__main__.TestArryCalc) ... ok
test_getter (__main__.TestArryCalc) ... ERROR
test_last (__main__.TestArryCalc) ... FAIL

======================================================================
ERROR: test_getter (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_F4.py", line 40, in test_getter
    test_getter_a = self.adapterSetting(0,0,0, TC, TC + '_a')
AttributeError: 'TestArryCalc' object has no attribute 'adapterSetting'

======================================================================
FAIL: test_last (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_F4.py", line 73, in test_last
    self.assertEqual(3, test_last_b.last())
AssertionError: 3 != 1

----------------------------------------------------------------------
Ran 4 tests in 0.051s

FAILED (failures=1, errors=1)
