test_avg (__main__.TestArryCalc) ... ok
test_first (__main__.TestArryCalc) ... FAIL
test_getter (__main__.TestArryCalc) ... ERROR
test_last (__main__.TestArryCalc) ... ok

======================================================================
ERROR: test_getter (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_F3.py", line 40, in test_getter
    test_getter_a = self.adapterSetting(0,0,0, TC, TC + '_a')
AttributeError: 'TestArryCalc' object has no attribute 'adapterSetting'

======================================================================
FAIL: test_first (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_F3.py", line 60, in test_first
    self.assertEqual(1, test_first_b.first())
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 4 tests in 0.051s

FAILED (failures=1, errors=1)
