test_avg (__main__.TestArryCalc) ... ok
test_first (__main__.TestArryCalc) ... ok
test_getter (__main__.TestArryCalc) ... ERROR
test_last (__main__.TestArryCalc) ... ok

======================================================================
ERROR: test_getter (__main__.TestArryCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in test_getter
    test_getter_a = self.adapterSetting(0,0,0, TC, TC + '_a')
AttributeError: 'TestArryCalc' object has no attribute 'adapterSetting'

----------------------------------------------------------------------
Ran 4 tests in 0.052s

FAILED (errors=1)
